kind: ReplicationController
apiVersion: v1
metadata:
  name: replication
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080 
              hostPort: 8080 
    
  